wiremock:
  server:
    files:
    stubs:
      - file:build/stubs/**/mappings/**/*.json
    port: 6565
server:
  port: 12306
github:
  host: https://api.github.com
google:
  host: https://api.github.com
spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/parkinglot
#    driverClassName: com.mysql.jdbc.Driver
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: create
