wiremock:
  server:
    files:
    stubs:
      - file:build/stubs/**/mappings/**/*.json
    port: 6565
server:
  port: 12306
github:
  host: https://api.github.com
google:
  host: https://api.github.com
env:
  profile: "${SPRINGPROFILE}"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parkinglot
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
#    data: classpath:data/import.sql
  flyway:
    enabled: false
#  jpa:
#    hibernate:
#      ddl-auto: create

