/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parking.mock.server;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.contract.wiremock.AutoConfigureWireMock;

@SpringBootApplication
//@AutoConfigureWireMock
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
